### ISSUE TITLE
Incorrect available method detection

### ISSUE THREAD

**Issue by Flanker72** [Akumzy/nedb-async#9]
@Akumzy After refactor this line contains invalid expression: https://github.com/Akumzy/nedb-async/blob/master/src/util.ts#L25 - all available methods cause error in console like: `Error: sort is not recognized, available methods are sort,limit,skip`

Needs to add `NOT` check like this:

```
if (!valid.includes(method)) {
```

**Comment by Akumzy** [comment]
@Flanker72 nice catch that was a mistake
